import { api } from './api.js';
import { openModal } from './modal.js';
let currentModel = '';
const $ = id => document.getElementById(id);
const node=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;};
function open(){const modal=openModal('Optional AI story direction'),body=modal.body,footer=modal.footer,close=modal.close;body.append(node('p','The validated case engine is fully playable without an API key. When configured, OpenRouter directs a new title, opening, atmosphere, character tensions, and interview voice for each selected cast. It never decides facts, rooms, evidence, or the solution.'));
const key=document.createElement('input');key.type='password';key.placeholder='OpenRouter key (optional)';const model=document.createElement('input');model.placeholder='Model ID (optional)';const temp=document.createElement('input');temp.type='number';temp.min='0';temp.max='2';temp.step='.05';temp.value='.8';body.append(field('API key',key),field('Model',model),field('Temperature',temp));const status=node('p','','muted');status.setAttribute('aria-live','polite');const search=node('button','Search available models','secondary');search.type='button';search.addEventListener('click',async()=>{status.textContent='Searching…';try{const result=await api.models(model.value);results.replaceChildren();result.models.slice(0,20).forEach(item=>{const b=node('button',`${item.name} (${item.id})`,'model-choice');b.type='button';b.addEventListener('click',()=>{model.value=item.id;currentModel=item.id;status.textContent='Model selected.';});results.append(b);});status.textContent=`${result.models.length} models returned.`;}catch(e){status.textContent=e.message;status.classList.add('error');}});const results=node('div',undefined,'model-results');body.append(search,status,results);const save=node('button','Save settings','primary');save.type='button';save.addEventListener('click',async()=>{try{const payload={temperature:Number(temp.value)};if(key.value.trim())payload.api_key=key.value.trim();if(model.value.trim())payload.model=model.value.trim();await api.saveSettings(payload);close();}catch(e){status.textContent=e.message;status.classList.add('error');}});footer.append(save);api.settings().then(data=>{key.placeholder=data.api_key_set?'Key already stored — enter only to replace':'OpenRouter key (optional)';model.value=data.model||'';currentModel=model.value;temp.value=data.temperature??.8;}).catch(()=>{});}
function field(label,input){const l=node('label',label);l.append(input);return l;}
export function initSettings(){$('title-settings').addEventListener('click',open);$('setup-settings').addEventListener('click',open);$('game-settings').addEventListener('click',open);}
